[window]
opacity = 0.75

[window.dimensions]
columns = 70
lines = 20

[font]
size = 9.5

[font.normal]
family = "Hack Nerd Font Mono"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#222222"
foreground = "#DBDBDB"

[colors.normal]
black   = "#000000"
red     = "#DA3436"
green   = "#69BE50"
yellow  = "#EAE234"
blue    = "#6274C6"
magenta = "#E3598E"
cyan    = "#7FC5D2"
white   = "#DBDBDB"


[colors.bright]
black   = "#555555"
red     = "#F07576"
green   = "#9FD68F"
yellow  = "#F0EB75"
blue    = "#A8B1D7"
magenta = "#D4AFD3"
cyan    = "#B2DFE1"
white   = "#F2F2F2"
