customCommands:
  - key: I
    command: git_show_new_term {{.SelectedLocalCommit.Hash}}
    description: Show commit in new terminal
    output: none
    context: commits

git:
  paging:
    colorArg: always
    pager: delta --paging=never
    useConfig: false
gui:
  nerdFontsVersion: "3"
