customCommands:
  - key: I
    command: git_show_new_term {{.SelectedLocalCommit.Hash}}
    description: Show commit in new terminal
    output: none
    context: commits

git:
  pagers:
    - colorArg: always
      pager: delta --paging=never

gui:
  nerdFontsVersion: "3"
