#!/bin/bash
#
# Reset all temporary commits of the current backup branch and checkout to the main branch. After this, the backup branch will be deleted.

set -e

source ~/.local/custom_scripts/libs/scripts.sh

# Runs all command in the current directory
scripts_cd_to_invoke_dir

# Check if the current commit is a temporary.
#
# Return 'y' if it is a temporary commit, 'n' otherwise.
is_commit_temporary() {
	local current_commit_title=$(git show --oneline --summary | sed -n 1p)

	[[ "$current_commit_title" =~ tmp\(auto-backup\): ]] && echo -n 'y' || echo -n 'n'
}

# Delete the current commit if it is a temporary commit.
reset_temporary_commit() {
	if [[ $(is_commit_temporary) == 'y' ]]; then
		git reset HEAD^1
	else
		return 1 # Not a temporary commit
	fi
}

# The user must be on a temporary branch
current_branch=$(git branch --show-current)
if ! [[ "$current_branch" =~ ^tmp\..*\.autogenerated.doNotUse$ ]]; then
	echo 'You are not on a temporary branch.' 1>&2
	exit 1
fi

# Delete all temporary commits.
while [[ true ]]; do
	if [[ $(is_commit_temporary) == 'y' ]]; then
		reset_temporary_commit
	else
		break
	fi
done

# Checkout to the main branch and delete the temporary branch
git checkout main || git checkout master
git branch --delete "$current_branch"
