initFields:
  author: User Name
  description: Project description
  keywords: "[ \"keyword\" ]"
  main: index.js
  scripts:
    start: node server.js

initLicense: MIT

initVersion: 1.0.0

nodeLinker: pnp

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.1.1.cjs
